// This is a placeholder for actual Prisma types.
// In a real application, this would be generated by Prisma.

export type Event = {
  id: string;
  title: string;
  date: Date;
  location: string;
  type: 'TOURNAMENT' | 'CERTIFICATION';
};
