// This is a placeholder for actual Prisma types.
// In a real application, this would be generated by Prisma.

export type Event = {
  id: string;
  title: string;
  date: string; // ISO string
  location: string;
  type: 'TOURNAMENT' | 'CERTIFICATION';
};

export type EventViewModel = Event & {
  formattedDate: string;
};
